fix(esm): Fix bug using from esm modules
When this module is required from esm, then caller()
returns a path that's prefixed by `file:`.

That causes an error like this
`UNCAUGHTEXCEPTION Error: Cannot find module '/Users/jacharles/dev_xo/loggernodeweb/node_modules/@infra/paypalize/file:/Users/jacharles/dev_xo/loggernodeweb/config/config.json`

This commit fixes that by removing the `file:` prefix added by the `caller()` module.